//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP2chan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KP2chan.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2CATO.
        /// </summary>
        internal static string entryDisableButton {
            get {
                return ResourceManager.GetString("entryDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO disabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryDisabled {
            get {
                return ResourceManager.GetString("entryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO disabled for {0} entries..
        /// </summary>
        internal static string entryDisabledForMultiple {
            get {
                return ResourceManager.GetString("entryDisabledForMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO disabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryDisabledForSingle {
            get {
                return ResourceManager.GetString("entryDisabledForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2CATO.
        /// </summary>
        internal static string entryEnableButton {
            get {
                return ResourceManager.GetString("entryEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO enabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryEnabled {
            get {
                return ResourceManager.GetString("entryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO enabled for {0} entries..
        /// </summary>
        internal static string entryEnabledForMultiple {
            get {
                return ResourceManager.GetString("entryEnabledForMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO enabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryEnabledForSingle {
            get {
                return ResourceManager.GetString("entryEnabledForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2CATO.
        /// </summary>
        internal static string groupDisableButton {
            get {
                return ResourceManager.GetString("groupDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO disabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupDisabled {
            get {
                return ResourceManager.GetString("groupDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2CATO.
        /// </summary>
        internal static string groupEnableButton {
            get {
                return ResourceManager.GetString("groupEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO enabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupEnabled {
            get {
                return ResourceManager.GetString("groupEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2CATO everywhere.
        /// </summary>
        internal static string mainDisableButton {
            get {
                return ResourceManager.GetString("mainDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO disabled for all entries..
        /// </summary>
        internal static string mainDisabled {
            get {
                return ResourceManager.GetString("mainDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 2CATO everywhere.
        /// </summary>
        internal static string mainEnableButton {
            get {
                return ResourceManager.GetString("mainEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] 2CATO enabled for all entries..
        /// </summary>
        internal static string mainEnabled {
            get {
                return ResourceManager.GetString("mainEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP2chan.
        /// </summary>
        internal static string pluginName {
            get {
                return ResourceManager.GetString("pluginName", resourceCulture);
            }
        }
    }
}
