//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP2chan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KP2chan.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto-Type everywhere.
        /// </summary>
        internal static string allATDisable {
            get {
                return ResourceManager.GetString("allATDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type disabled for all entries..
        /// </summary>
        internal static string allATDisabled {
            get {
                return ResourceManager.GetString("allATDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Type everywhere.
        /// </summary>
        internal static string allATEnable {
            get {
                return ResourceManager.GetString("allATEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type enabled for all entries..
        /// </summary>
        internal static string allATEnabled {
            get {
                return ResourceManager.GetString("allATEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable TCATO everywhere.
        /// </summary>
        internal static string allTcatoDisable {
            get {
                return ResourceManager.GetString("allTcatoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO disabled for all entries..
        /// </summary>
        internal static string allTcatoDisabled {
            get {
                return ResourceManager.GetString("allTcatoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCATO everywhere.
        /// </summary>
        internal static string allTcatoEnable {
            get {
                return ResourceManager.GetString("allTcatoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO enabled for all entries..
        /// </summary>
        internal static string allTcatoEnabled {
            get {
                return ResourceManager.GetString("allTcatoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Type automatically.
        /// </summary>
        internal static string atAutoEnable {
            get {
                return ResourceManager.GetString("atAutoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type disabled for {0} entries..
        /// </summary>
        internal static string entriesATDisabled {
            get {
                return ResourceManager.GetString("entriesATDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type enabled for {0} entries..
        /// </summary>
        internal static string entriesATEnabled {
            get {
                return ResourceManager.GetString("entriesATEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO disabled for {0} entries..
        /// </summary>
        internal static string entriesTcatoDisabled {
            get {
                return ResourceManager.GetString("entriesTcatoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO enabled for {0} entries..
        /// </summary>
        internal static string entriesTcatoEnabled {
            get {
                return ResourceManager.GetString("entriesTcatoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto-Type.
        /// </summary>
        internal static string entryATDisable {
            get {
                return ResourceManager.GetString("entryATDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type disabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryATDisabled {
            get {
                return ResourceManager.GetString("entryATDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Type.
        /// </summary>
        internal static string entryATEnable {
            get {
                return ResourceManager.GetString("entryATEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type enabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryATEnabled {
            get {
                return ResourceManager.GetString("entryATEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable TCATO.
        /// </summary>
        internal static string entryTcatoDisable {
            get {
                return ResourceManager.GetString("entryTcatoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO disabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryTcatoDisabled {
            get {
                return ResourceManager.GetString("entryTcatoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCATO.
        /// </summary>
        internal static string entryTcatoEnable {
            get {
                return ResourceManager.GetString("entryTcatoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO enabled for entry &quot;{0}&quot;..
        /// </summary>
        internal static string entryTcatoEnabled {
            get {
                return ResourceManager.GetString("entryTcatoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto-Type.
        /// </summary>
        internal static string groupATDisable {
            get {
                return ResourceManager.GetString("groupATDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type disabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupATDisabled {
            get {
                return ResourceManager.GetString("groupATDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto-Type.
        /// </summary>
        internal static string groupATEnable {
            get {
                return ResourceManager.GetString("groupATEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] Auto-Type enabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupATEnabled {
            get {
                return ResourceManager.GetString("groupATEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable TCATO.
        /// </summary>
        internal static string groupTcatoDisable {
            get {
                return ResourceManager.GetString("groupTcatoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO disabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupTcatoDisabled {
            get {
                return ResourceManager.GetString("groupTcatoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCATO.
        /// </summary>
        internal static string groupTcatoEnable {
            get {
                return ResourceManager.GetString("groupTcatoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [KP2chan] TCATO enabled for group &quot;{0}&quot;..
        /// </summary>
        internal static string groupTcatoEnabled {
            get {
                return ResourceManager.GetString("groupTcatoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Type / TCATO.
        /// </summary>
        internal static string menuItemText {
            get {
                return ResourceManager.GetString("menuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCATO automatically.
        /// </summary>
        internal static string tcatoAutoEnable {
            get {
                return ResourceManager.GetString("tcatoAutoEnable", resourceCulture);
            }
        }
    }
}
